# https://gleam.run/writing-gleam/gleam-toml/.

name = "backend"
version = "1.0.0"

[dependencies]
shared = { path = "../shared/"}
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
gleam_erlang = ">= 0.32.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
mist = ">= 4.0.0 and < 5.0.0"
glanoid = ">= 1.0.1 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
