# https://gleam.run/writing-gleam/gleam-toml/.

name = "shared"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
glanoid = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
